theme: jekyll-theme-minimal
title: Profir-Petru Pârțachi's Homepage
description: I am a PhD Student at University College London working with [Dr Earl T. Barr](http://earlbarr.com/) on improving project health by applying Machine Learning to problems from Software Engineering. Some of my projects are listed on this page.
logo: /profile_pic.png
